version: "3.7"

services:
  service:
    image: ruby:3.2.2-slim-buster
    platform: linux/amd64
    volumes:
      - ./:/app:delegated
    working_dir:
      /app
    command:
      bin/foreman_start Procfile.dev
